# Generated by Django 3.1.5 on 2026-04-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0005_auto_20260419_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisalform',
            name='employeeId',
        ),
        migrations.RemoveField(
            model_name='cpdaadvanceform',
            name='employeeId',
        ),
        migrations.RemoveField(
            model_name='cpdareimbursementform',
            name='employeeId',
        ),
        migrations.RemoveField(
            model_name='ltcform',
            name='employeeId',
        ),
    ]
