# Generated by Django 3.1.5 on 2026-04-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr2', '0006_auto_20260419_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalform',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisalform',
            name='status',
            field=models.CharField(db_index=True, default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cpdaadvanceform',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpdaadvanceform',
            name='status',
            field=models.CharField(db_index=True, default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cpdareimbursementform',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpdareimbursementform',
            name='status',
            field=models.CharField(db_index=True, default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='vacation_leave_balance',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='half_day_slot',
            field=models.CharField(blank=True, choices=[('AM', 'Morning Slot (Before 2:00 PM)'), ('PM', 'Afternoon Slot (After 2:00 PM)')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='leaveform',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveperyear',
            name='vacation_leave',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='ltcform',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ltcform',
            name='status',
            field=models.CharField(db_index=True, default='Pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='leaveform',
            constraint=models.UniqueConstraint(condition=models.Q(state__in=['submitted', 'hod_approved', 'admin_approved', 'sanction_approved', 'final_approved']), fields=('employee', 'leaveStartDate'), name='unique_active_leave_start_per_employee'),
        ),
    ]
